
# Build matrix
language: node_js

gemfile:
  - Gemfile

matrix:
  include:
    # Run tests in Node.js 6.x
    - node_js: '6'

# cache the node modules
cache:
  directories:
    - node_modules

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# build notification
notifications:
  email:
    - feds@springernature.com

# Build script
script:
  - 'npm run build'

# Auto-publish to NPM
after_success:
  - 'if [[ $TRAVIS_PULL_REQUEST = "false" ]]; then PUBLISH_PACKAGE=true; else PUBLISH_PACKAGE=false; fi'
  - 'echo "Pull Request: $TRAVIS_PULL_REQUEST" && echo "Node: $TRAVIS_NODE_VERSION" && echo "Publish? $PUBLISH_PACKAGE"'
  - 'if [ $PUBLISH_PACKAGE = "true" ]; then npm run publish; fi'
