
# Build matrix
language: node_js

gemfile:
  - Gemfile

# Save common build configurations as shortcuts, so we can reference them later
addons_shortcuts:
  addons_gcc48: &gcc48
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-4.8
        - g++-4.8

matrix:
  include:

    # Run tests in Node.js 6.x (dependencies require GCC 4.8)
    - node_js: '6'
      addons: *gcc48

# cache the node modules
cache:
  directories:
    - node_modules

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# build notification
notifications:
  email:
    - feds@springernature.com

# Before install
before_install:
  # Use GCC 4.8 if it's available
  - 'if [ ! `which gcc-4.8` == "" ]; then export CXX=g++-4.8 && export CC=gcc-4.8; fi'

# Build script
script:
  - 'npm run build'

# Auto-publish to NPM
after_success:
  - 'if [[ $TRAVIS_PULL_REQUEST = "false" ]]; then PUBLISH_PACKAGE=true; else PUBLISH_PACKAGE=false; fi'
  - 'echo "Pull Request: $TRAVIS_PULL_REQUEST" && echo "Node: $TRAVIS_NODE_VERSION" && echo "Publish? $PUBLISH_PACKAGE"'
  - 'if [ $PUBLISH_PACKAGE = "true" ]; then npm run publish; fi'

