#!/usr/bin/env bash

node_modules/.bin/lerna bootstrap
cd packages/snc-box
#PKG_NAME=`node -p "require('./package.json').name"`
#PKG_VERSION=`node -p "require('./package.json').version"`
FILE_NAME=`npm pack`
curl -F "package=@$FILE_NAME" https://push.fury.io/$1/nature/